{
 "title": "gps_temp",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "Vehicle Tracking",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lat as value, $__time(timestp) FROM gps WHERE $__timeFilter(timestp) ORDER BY timestp ASC"
    },
    {
     "rawSql": "SELECT longi as value, $__time(timestp) FROM gps WHERE $__timeFilter(timestp) ORDER BY timestp ASC"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 } },
  {
   "title": "Temperature_Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT Temperature, timestp FROM gps_temp.sensor where mac_id=\"0081F96B490D\" order by timestp asc"
    }
   ]
  },
  {
   "title": "Humidity_Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "iot_db",
     "rawSql": "SELECT Humidity, timestp FROM gps_temp.sensor where mac_id=\"0081F96B490D\" order by timestp asc"
    }
   ]
  }
 ]
}